### ISSUE TITLE
[Question] google-gemini上游存在，本项目好像没有成功?

### ISSUE THREAD

**Issue by JYbill** [Loyalsoldier/v2ray-rules-dat#376]
- 配置
```yaml
# ...
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
```
- script
```ts
// 这里是伪代码，代码自己验证过可以正常运行
config["rules"].unshift(
    `GEOSITE,openai,${proxyUSAField}`,
    // `DOMAIN-KEYWORD,gemini,${proxyUSAField}`, // 这块好像没有生成成功，用于代替
    `GEOSITE,google-gemini,${proxyUSAField}`, // ❌！！！
    `GEOSITE,anthropic,${proxyUSAField}`
);
```
![image](https://github.com/user-attachments/assets/d1182617-1a8f-4505-8ceb-c4e9e1ef120f)
