### ISSUE TITLE
services.googleapis.cn命中cn规则，但在解压出的cn规则文件中未找到

### ISSUE THREAD

**Issue by GoFightNow** [Loyalsoldier/v2ray-rules-dat#394]
我手机在wifi环境下透明代理，使用google play，然后就会触发访问services.googleapis.cn这个域名，这个域名的DNS请求被发在了国内的域名解析服务器上，我想应该是nameserver-policy->geosite:cn,private,apple导致的，我找到了我程序使用的geosite.dat和geo解析工具，我使用geo工具解析查看这个域名在cn规则下，但是我在将cn提取出来在domain和full找不到，在regex规则下也没找到，不太懂为什么会找不到，是因为每个规则之间有包含关系吗，还是因为其他？我会在下面提供我的各项设置和关于geosite的一些行动结果

先挂上我使用的版本
openclash: v0.46.033-beta
metacore: alpha-g59a2b24
geosite: [Loyalsoldier-testingcf-jsdelivr-Version(默认)](https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat)
geo工具: [geo](https://github.com/MetaCubeX/geo/releases)

挂上我配置中关于dns部分
```yaml
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
  - "https://1.1.1.1/dns-query#\U0001F680 节点选择"
  - "https://1.0.0.1/dns-query#\U0001F680 节点选择"
  - "https://dns.google/dns-query#\U0001F680 节点选择"
  - "tls://dns.google#\U0001F680 节点选择"
  nameserver-policy:
    geosite:cn,private,apple:
    - https://223.5.5.5/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
    - tls://223.5.5.5
    - tls://dot.pub
  proxy-server-nameserver:
  - https://223.5.5.5/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - tls://223.5.5.5
  - tls://dot.pub
```

openclash的debug日志
```bash
root@OpenWrt:~# cat /tmp/openclash.log | grep -C 2 'services.googleapis.cn'
time="2024-11-03T07:45:51.710713243Z" level=debug msg="TProxy local conn listener exit.. rAddr=112.49.244.61:26148 lAddr=192.168.31.30:61501"
time="2024-11-03T07:45:51.710731084Z" level=debug msg="Closing TProxy local conn... lAddr=192.168.31.30:61501 rAddr=112.49.244.61:26148"
time="2024-11-03T07:45:55.364207789Z" level=debug msg="[DNS] resolve services.googleapis.cn A from tls://dot.pub:853"
time="2024-11-03T07:45:55.364266746Z" level=debug msg="[DNS] cache hit dot.pub --> [120.53.53.53] A, expire at 2024-11-03 07:55:43"
time="2024-11-03T07:45:55.364284595Z" level=debug msg="[DNS] resolve services.googleapis.cn A from https://223.5.5.5:443/dns-query"
time="2024-11-03T07:45:55.364293232Z" level=debug msg="[DNS] resolve services.googleapis.cn A from https://doh.360.cn:443/dns-query"
time="2024-11-03T07:45:55.364450068Z" level=debug msg="[DNS] resolve services.googleapis.cn A from https://doh.pub:443/dns-query"
time="2024-11-03T07:45:55.364503862Z" level=debug msg="[DNS] cache hit doh.360.cn --> [101.199.254.118 123.6.48.18 112.65.69.15] A, expire at 2024-11-03 07:45:53"
time="2024-11-03T07:45:55.364295948Z" level=debug msg="[DNS] resolve services.googleapis.cn A from tls://223.5.5.5:853"
time="2024-11-03T07:45:55.364549512Z" level=debug msg="[DNS] resolve doh.360.cn A from udp://1.0.0.1:53"
time="2024-11-03T07:45:55.364577625Z" level=debug msg="[DNS] resolve doh.360.cn A from udp://8.8.8.8:53"
time="2024-11-03T07:45:55.364626112Z" level=debug msg="[DNS] resolve doh.360.cn A from udp://223.5.5.5:53"
time="2024-11-03T07:45:55.364643836Z" level=debug msg="[DNS] resolve doh.360.cn A from udp://114.114.114.114:53"
time="2024-11-03T07:45:55.380942362Z" level=debug msg="[DNS] services.googleapis.cn --> [114.250.67.34] A from https://223.5.5.5:443/dns-query"
time="2024-11-03T07:45:55.385824634Z" level=debug msg="[DNS] doh.360.cn --> [123.6.48.18 101.199.254.118 112.65.69.15] A from udp://223.5.5.5:53"
time="2024-11-03T07:45:55.403770696Z" level=debug msg="[Rule] use default rules"
time="2024-11-03T07:45:55.403942947Z" level=debug msg="[DNS] cache hit 机场域名 --> [机场IP] A, expire at 2024-11-03 07:46:02"
time="2024-11-03T07:45:55.455555568Z" level=info msg="[TCP] 192.168.31.105:46334 --> services.googleapis.cn:443 match DomainKeyword(google) using 🚀 节点选择[🇭🇰 [v1] 香港・08]"
```

我使用geo工具在geosite.dat查询services.googleapis.cn的结果
```
C:\Users\UserName\Desktop\abc>geo-windows-amd64.exe look --no-resolve -f C:\Users\UserName\Desktop\abc\geosite.dat services.googleapis.cn
🔎Querying from [C:\Users\UserName\Desktop\abc\geosite.dat]
🎉Query finished in 579.4755ms!
Total 7 results (GeoSite codes):
  china-list gfw tld-cn geolocation-!cn google category-companies cn
```

我提取cn用的命令
```
C:\Users\UserName\Desktop\abc>geo-windows-amd64.exe unpack site -d out -c cn C:\Users\UserName\Desktop\abc\geosite.dat
```

我解压出来的cn文件
[cn.txt](https://github.com/user-attachments/files/17609732/cn.txt)
